name: duitku_app
description: "DuitKu — Aplikasi pencatat keuangan pribadi versi native."
publish_to: 'none'

version: 1.2.9+10

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  shared_preferences: ^2.3.3
  provider: ^6.1.2
  intl: ^0.19.0
  fl_chart: ^0.69.0
  image_picker: ^1.1.2
  path_provider: ^2.1.4
  connectivity_plus: ^6.0.5
  mobile_scanner: ^7.4.0
  qr_flutter: ^4.1.0
  uuid: ^4.4.2
  home_widget: ^0.7.0
  pdf: ^3.11.1
  printing: ^5.13.2
  open_file: ^3.3.2
  url_launcher: ^6.3.0
  google_mlkit_text_recognition: ^0.14.0
  package_info_plus: ^10.2.1
  video_player: ^2.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.2
  flutter_native_splash: ^2.4.3

flutter:
  uses-material-design: true
  assets:
    - assets/icon/logo.png
    - assets/icon/logo_splash.png

flutter_launcher_icons:
  android: true
  image_path: "assets/icon/logo.png"
  adaptive_icon_background: "#F6F7F9"
  adaptive_icon_foreground: "assets/icon/logo.png"
  min_sdk_android: 21


